# Generated by Django 4.2.6 on 2023-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
